
---
name: Create and publish a container

on:
  push:
    branch:
      - main
  workflow_dispatch: {}

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to the gcr registry
        uses: docker/login-action@v2.0.0
        with:           
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
            
      - name: Log in to the Dockerhub registry
        uses: docker/login-action@v2.0.0
        with:
          registry: docker.io
          username: soerensoerensen
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - name: Extract metadata for container
        id: gcr
        uses: docker/metadata-action@v4.1.1
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=raw,value={{ branch}}-{{date 'YYYYMMDDHHmmss'}}
            type=ref,event=branch
            type=ref,event=pr
            type=raw,value=latest,enable={{is_default_branch}}


      - name: Extract metadata for container
        id: dockerhub
        uses: docker/metadata-action@v4.1.1
        with:
          images: docker.io/soerensoerensen/network-swiss-knife
          tags: |
            type=raw,value={{ branch}}-{{date 'YYYYMMDDHHmmss'}}
            type=ref,event=branch
            type=ref,event=pr
            type=raw,value=latest,enable={{is_default_branch}}

      - name: Build and push container image
        uses: docker/build-push-action@v3.2.0
        with:
          context: .
          push: true
          tags: ${{ steps.dockerhub.outputs.tags }}
          labels: ${{ steps.dockerhub.outputs.labels }}
          
      - name: Build and push container image
        uses: docker/build-push-action@v3.2.0
        with:
          context: .
          push: true
          tags: ${{ steps.gcr.outputs.tags }}
          labels: ${{ steps.gcr.outputs.labels }}
